<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="terms" nsURI="http://st.int.tud.org/mbt/terms" nsPrefix="terms">
  <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctorTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberTerm" abstract="true" interface="true"
      eSuperTypes="#//Term"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatTerm" eSuperTypes="#//NumberTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerTerm" eSuperTypes="#//NumberTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongTerm" eSuperTypes="#//NumberTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="ecore:EClass mbt.ecore#//functions/IFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass mbt.ecore#//core/AbstractModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containment" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolTerm" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermVariable" eSuperTypes="#//Term mbt.ecore#//core/IContextVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
